### ISSUE TITLE
部署文档

### ISSUE THREAD

**Issue by songyinjun2008** [jwgl/bell-tm-server#39]
你好,我刚接触这个项目,在部署执行时,有些疑问.
1 bell-db下有很多sql文件,执行顺序有要求吗. 
2 些表,是通过grails创建的,哪些sql文件是在项目启动前执行,哪些是在启动后执行?
3 application.yml 里面没有数据库地址/用户名/密码的配置项, 这些项应该在哪里修改?
4  除了bell-tm-core提到的6个模块, 还有哪些模块是需要运行的? (例如bell-core下面的模块只需要编译安装就行)
谢谢

**Comment by todoubaba** [comment]
1、sync-fdw.sql前面部分是创建数据库，之后执行ea-type.sql，其他sql是运行程序创建表后执行。
2、创建环境变量BELL_CONFIG_LOCATION，指向一个目录，创建配置文件<project-name.yml>。
3、基本模块包括都在bell-tm-core下面。
4、这个repo已经不用了，有问题请在bell-tm-core下提问。
